### ISSUE TITLE
Running net2 without a GPU

### ISSUE THREAD

**Issue by marsplus** [dnouri/kfkd-tutorial#1]
First I really appreciate your effort in making this tutorial and nolearn wrappers. With nolearn I can just twist deep neural networks as easily as with scikit-learn. 

When I am going through your tutorial I encounter a problem. This problem happens when I fit X, y in net2, namely net2.fit(X, y). I got an error message, "CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None".   I don't have GPU on my Mac so I just modify the code from:

``` python
Conv2DLayer = layers.cuda_convnet.Conv2DCCLayer
MaxPool2DLayer = layers.cuda_convnet.MaxPool2DCCLayer
```

into:

``` python
Conv2DLayer = layers.Conv2DLayer
MaxPool2DLayer = layers.MaxPool2DLayer
```

Unfortunately new error occurs, and the error message is, "the batch size in the image (48) at run time is different than at build time (128) for the ConvOp."

I have already set the batch size to 128, but there is some weird batch size "48" in the error message. 

Could you please give me some advice about this problem? Should I give up running the code on my Mac and find a GPU?

**Comment by dnouri** [comment]
Forget about `force_even`.  It's totally unnecessary.  In this example, just set
```
    # ...
    input_shape=(None, 1, 96, 96),
    # ...
```

See https://github.com/dnouri/nolearn/issues/8#issuecomment-68504930
