### ISSUE TITLE
ERROR (theano.sandbox.cuda): nvcc compiler not found on $PATH. Check your nvcc installation and try again

### ISSUE THREAD

**Issue by andyyuan78** [dnouri/kfkd-tutorial#15]
I see the error as title when I run sudo python kfkd.py fit
ubgpu@ubgpu:~/big_data/kaggle/kaggle_Facial_Keypoints_Detection/kfkd-tutorial$ sudo python kfkd.py fit
[sudo] password for ubgpu: 
ERROR (theano.sandbox.cuda): nvcc compiler not found on $PATH. Check your nvcc installation and try again.
left_eye_center_x            7039
left_eye_center_y            7039
right_eye_center_x           7036
right_eye_center_y           7036
left_eye_inner_corner_x      2271
left_eye_inner_corner_y      2271
left_eye_outer_corner_x      2267

I pretty sure the CUDA7 is installed and works well in example of caffe, cuda-convnet or theano;

also:
ubgpu@ubgpu:~$ which nvcc
/usr/local/cuda/bin/nvcc

my  device is GTX970.

**Comment by dnouri** [comment]
Why are you running kfkd.py with sudo?  You probably don't have nvcc on your path when you sudo.

**Comment by andyyuan78** [comment]
thanks you reminder!
