### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by JourneyGo** [dnouri/kfkd-tutorial#18]
Hi,
While I was following this tutorial, After done set up my vitual enviorment and started to run mnist.py,
a syntax error occured  
```
Traceback (most recent call last):
  File "mnist.py", line 13, in <module>
    import lasagne
  File "/home/gaoqi/ENV/src/lasagne/lasagne/__init__.py", line 8, in <module>
    from . import objectives
  File "/home/gaoqi/ENV/src/lasagne/lasagne/objectives.py", line 22
    _valid_aggregation = {None, 'mean', 'sum'}
                              ^
SyntaxError: invalid syntax
```
Where have no such error.

If this could be the reason ,a warning was give at the begining said, 
Moudle scipy.linalg.blas.fblas is deprecated ,use scipy.linalg.blas instead DeprecationWarning

Or it's my problem ,will someone there could help?

best,
Qi

**Comment by dnouri** [comment]
You must be running Python 2.6 or earlier, which I'm afraid isn't supported by Lasagne.

**Comment by JourneyGo** [comment]
Yes, I've updated Python to 2.7.3 and this problem just vanished. Thank U
