### ISSUE TITLE
Theano for non-CUDA GPU

### ISSUE THREAD

**Issue by CecileSun** [dnouri/kfkd-tutorial#22]
Hi Daniel,

First of all, thank you for this tutorial. I am new to Kaggle, and this tutorial really give me a good sense of how to form a good solution.

My question is, I am running a Mac Yosemite (10.10) upgraded from SnowLeopard (10.6), so I only have 1 graphics card, which is a Intel HD Graphics 3000 (so no CUDA graphics card). I would like to know if I can still configure it to run Theano without paying for anything.

Thank you very much!

Cecile

**Comment by dnouri** [comment]
> My question is, I am running a Mac Yosemite (10.10) upgraded from 
> SnowLeopard (10.6), so I only have 1 graphics card, which is a Intel 
> HD Graphics 3000 (so no CUDA graphics card). I would like to know if 
> I can still configure it to run Theano without paying for anything.
> 
You won't be able to use the GPU.  Running the app on a CPU isn't going 
to make you happy, it's very slow.
