### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by syronanm** [dnouri/kfkd-tutorial#23]
Hi 

I have specially installed python and all the packages in order to follow your tutorial

I am working with my laptop on windows 8.1, Python 2.7.10.

But when I try to launch mnist.py some errors occurs : 
 
![bug1](https://cloud.githubusercontent.com/assets/6012645/9837686/7675c854-5a47-11e5-9014-cec4c4e97d34.png)
![bug2](https://cloud.githubusercontent.com/assets/6012645/9837688/7df99fec-5a47-11e5-8e31-9de590ad0c86.png)

Do you have any idea for helping me ?

Thanks,

RSM

**Comment by dnouri** [comment]
Try the Theano mailing list.  And make sure you provide the error information as text, not as images!
