### ISSUE TITLE
Error in tutorial

### ISSUE THREAD

**Issue by josephmisiti** [dnouri/kfkd-tutorial#24]
Thanks a lot for this tutorial - it is very helpful. Unfortunately there are a few problems with it right now, one which I was able to fix, and one I was not able to fix.
## Issue I Fixed

If you install the software as recommend, I believe you get the following error with an import:

```
ubuntu@ip-172-31-16-25:~/focal_points$ python -c 'from nolearn.lasagne import NeuralNet'
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/ubuntu/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Using gpu device 0: GRID K520 (CNMeM is disabled)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/nolearn/lasagne.py", line 11, in <module>
    from lasagne.objectives import mse
ImportError: cannot import name mse
```

This is fixed by installing `nolearn==0.6adev`, of which you have to install it from source, not via `pip`, (at least I was not able to install it via pip, but I submitted another pull request for that one).
## Issue Still Unresolved

The issue that is currently unresolved is installation instructions no longer work.  Specifically your AMI is now broken, most likely because Amazon updated GPU drivers but regardless it no longer works. If you follow along in the [instructions](https://github.com/wendykan/AWSGPU_DeepLearning) in `setup.sh` in part 6 of your [tutorial](https://www.kaggle.com/c/facial-keypoints-detection/details/deep-learning-tutorial), the instance does seem to work either. I had use a different AMI to run your code.

[Let me know](https://twitter.com/josephmisiti) what I can do to help!

**Comment by xmen4u** [comment]
Here's what i've done: 
sudo pip uninstall nolearn
git clone https://github.com/dnouri/nolearn.git
cd nolearn
sudo python setup.py install

Hope this helps someone

**Comment by dnouri** [comment]
@josephmisiti I just tried to reproduce this issue by running the following commands:

```bash
$ virtualenv .
$ bin/pip install -r https://raw.githubusercontent.com/dnouri/kfkd-tutorial/master/requirements.txt
$ python kfkd.py run
```

But this seemed to work fine for me.  Any idea what I've done differently?

Wendy Kan from Kaggle is the one in charge of the AMI.  Please report your issue with the Amazon image to her: https://www.kaggle.com/wendykan

**Comment by dnouri** [comment]
Closing due to lack of response.
