### ISSUE TITLE
TypeError: cost must be a scalar！

### ISSUE THREAD

**Issue by Imorton-zd** [dnouri/kfkd-tutorial#25]
I have done as #16, but 'pip install -r https://raw.githubusercontent.com/dnouri/kfkd-tutorial/master/requirements.txt' also outputs an error 
![image](https://cloud.githubusercontent.com/assets/13865086/10508610/b45fd6ba-735a-11e5-97c9-3068d20beb25.png)

**Comment by dnouri** [comment]
Need to install git?
