### ISSUE TITLE
No Dropout after the last FC Layer

### ISSUE THREAD

**Issue by cancan101** [dnouri/kfkd-tutorial#4]
It looks like dropout is not being used here for the last FC layer: https://github.com/dnouri/kfkd-tutorial/blob/f79ee98facfba2755b7f6fdcddbc4b73c01d021d/kfkd.py#L188. Is that by design?

**Comment by dnouri** [comment]
Answered here: http://danielnouri.org/notes/2014/12/17/using-convolutional-neural-nets-to-detect-facial-keypoints-tutorial/#comment-1773759523
